### PR TITLE
Add `SerializeBits`/`DeserializeBits` derive macros

### PR DESCRIPTION
**Pull request by widberg**
Draft pr for issue #74

### CODE REVIEW

**Review by hecatia-elegua — CHANGES_REQUESTED** [review]
Thank you!
I will not hold this back a lot, but does internal deserialize code always look this complicated? :rofl:
It seems like you can do something better with the `deserialize_field_parts` inlined and maybe inverting the logic a bit.
You can try, but it would be enough to add tests for arb ints before merging, see comment.

**Comment by widberg** [comment]
Let me know if those tests look any better or if you have more cases you want me to add. I'll work on cleaning up the logic you pointed out before this gets merged. ime internal deserialize code is usually pretty complicated just because of how serde requires it to be implemented; if there is a better way I'd be happy to do it like that instead.

**Review by hecatia-elegua — APPROVED** [review]

**Comment by hecatia-elegua** [comment]
(running CI to run tests, feel free to clean up still)

**Review by hecatia-elegua — CHANGES_REQUESTED** [review]
Sorry, I was away again. The nightly test fail is not important rn, but your new tests are not actually running, I didn't realize this earlier. We can just change the workflow file to do `cargo test --workspace --features serde`.
Again something I could do myself, but I dislike when others fiddle around in my changeset, so I don't do so in others changesets either.

**Comment by hecatia-elegua** [comment]
We got it :)
Now I'll need to figure out how to handle the nightly stuff.

Thank you again.

**Pull request merged**
